export const ALL_CAR_REQUEST = "NEW_CAR_REQUEST"
export const ALL_CAR_SUCCESS = "NEW_CAR_SUCCESS"
export const ALL_CAR_FAIL = "NEW_CAR_FAIL"

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST"
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS"
export const CAR_DETAILS_FAIL = "CAR_DETAILS_FAIL"

export const COMPARE_CAR_REQUEST = "COMPARE_CAR_REQUEST"
export const COMPARE_CAR_SUCCESS = "COMPARE_CAR_SUCCESS"
export const COMPARE_CAR_FAIL = "COMPARE_CAR_FAIL"
