export const FAVORITE_CAR_LISTS_REQUEST = "FAVORITE_CAR_LISTS_REQUEST"
export const FAVORITE_CAR_LISTS_SUCCESS = "FAVORITE_CAR_LISTS_SUCCESS"
export const FAVORITE_CAR_LISTS_FAIL = "FAVORITE_CAR_LISTS_FAIL"

export const ADD_TO_FAVORITE_REQUEST = "ADD_TO_FAVORITE_REQUEST"
export const ADD_TO_FAVORITE_SUCCESS = "ADD_TO_FAVORITE_SUCCESS"
export const ADD_TO_FAVORITE_FAIL = "ADD_TO_FAVORITE_FAIL"
export const ADD_TO_FAVORITE_RESET = "ADD_TO_FAVORITE_RESET"
