export const FAQ_REQUEST = "FAQ_REQUEST"
export const FAQ_SUCCESS = "FAQ_SUCCESS"
export const FAQ_FAIL = "FAQ_FAIL"

export const CONTACT_REQUEST = "CONTACT_REQUEST"
export const CONTACT_SUCCESS = "CONTACT_SUCCESS"
export const CONTACT_FAIL = "CONTACT_FAIL"

export const TERM_AND_CONDITION_REQUEST = "TERM_AND_CONDITION_REQUEST"
export const TERM_AND_CONDITION_SUCCESS = "TERM_AND_CONDITION_SUCCESS"
export const TERM_AND_CONDITION_FAIL = "TERM_AND_CONDITION_FAIL"

export const DEALERS_REQUEST = "DEALERS_REQUEST"
export const DEALERS_SUCCESS = "DEALERS_SUCCESS"
export const DEALERS_FAIL = "DEALERS_FAIL"
