export const NEWS_REQUEST = "NEWS_REQUEST"
export const NEWS_SUCCESS = "NEWS_SUCCESS"
export const NEWS_FAIL = "NEWS_FAIL"

export const NEWS_DETAILS_REQUEST = "NEWS_DETAILS_REQUEST"
export const NEWS_DETAILS_SUCCESS = "NEWS_DETAILS_SUCCESS"
export const NEWS_DETAILS_FAIL = "NEWS_DETAILS_FAIL"
